name: Build Latest

on: [workflow_dispatch]
  
env:
  DOTNET_SDK_VERSION: '8.0.*'
  PROJECT_NAME: 'STS-Bcut'

jobs:

  build-win-x64-arm64:
    
    runs-on: windows-latest
    
    steps:
      
      - uses: actions/checkout@v1

      - name: Set up Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Set up dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - run: dotnet publish ${{ env.PROJECT_NAME }}.csproj -r win-x64 -c Release -o artifact-x64 -p:PublishSingleFile=true -p:PublishReadyToRun=true --self-contained true

      - name: Upload Artifact[win-x64]
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}_win-x64
          path: artifact-x64\${{ env.PROJECT_NAME }}.exe
